# Generated by Django 5.2.2 on 2026-04-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianresponse',
            name='sos_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.sosrequest'),
        ),
    ]
