# Generated by Django 6.0.7 on 2026-07-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('Harassment', 'Harassment'), ('Theft', 'Theft'), ('Suspicious Activity', 'Suspicious Activity'), ('Unsafe Route', 'Unsafe Route'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('commuter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.commuter')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.ridedetails')),
            ],
        ),
    ]
