# Generated by Django 6.0.7 on 2026-08-06 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
        ('user', '0002_incidentreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commuter',
            options={'verbose_name_plural': 'Commuters'},
        ),
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'verbose_name_plural': 'Incident Reports'},
        ),
        migrations.AlterModelOptions(
            name='ridedetails',
            options={'verbose_name_plural': 'Ride Details'},
        ),
        migrations.AlterModelOptions(
            name='sosrequest',
            options={'verbose_name': 'SOS Request', 'verbose_name_plural': 'SOS Requests'},
        ),
        migrations.RemoveField(
            model_name='commuter',
            name='email',
        ),
        migrations.AddField(
            model_name='ridedetails',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='commuter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='user.commuter'),
        ),
        migrations.AlterField(
            model_name='ridedetails',
            name='commuter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='user.commuter'),
        ),
        migrations.AlterField(
            model_name='sosrequest',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_requests', to='user.ridedetails'),
        ),
        migrations.AlterField(
            model_name='sosrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['lat', 'lng'], name='idx_incident_coords'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['timestamp'], name='idx_incident_timestamp'),
        ),
        migrations.AddIndex(
            model_name='ridedetails',
            index=models.Index(fields=['commuter', 'is_active'], name='idx_ride_commuter_active'),
        ),
        migrations.AddIndex(
            model_name='ridedetails',
            index=models.Index(fields=['start_time'], name='idx_ride_start_time'),
        ),
        migrations.AddIndex(
            model_name='ridedetails',
            index=models.Index(fields=['is_active'], name='idx_ride_active'),
        ),
        migrations.AddIndex(
            model_name='sosrequest',
            index=models.Index(fields=['status'], name='idx_sos_status'),
        ),
        migrations.AddIndex(
            model_name='sosrequest',
            index=models.Index(fields=['timestamp'], name='idx_sos_timestamp'),
        ),
    ]
