# Generated by Django 6.0.7 on 2026-08-07 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_commuter_options_alter_incidentreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('relationship', models.CharField(choices=[('Parent', 'Parent'), ('Spouse', 'Spouse'), ('Sibling', 'Sibling'), ('Friend', 'Friend'), ('Other', 'Other')], default='Other', max_length=20)),
                ('commuter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_contacts', to='user.commuter')),
            ],
            options={
                'verbose_name_plural': 'Trusted Contacts',
            },
        ),
    ]
